#!/usr/bin/bash

VMHOME="/home/user/virtual_machines"
IMAGES="/mnt/data0/images/"
WHICH="/usr/bin/which"

SUDO=`$WHICH sudo`
QEMU=`$WHICH qemu-system-x86_64`
BASENAME=`$WHICH basename`
DISK=`$BASENAME "$0" .sh`

if [[ ! -f "$VMHOME/$DISK.qcow2" ]]
then
  echo "disk $VMHOME/$DISK.qcow2 not found"
  echo "create disk:"
  echo "qemu-img create -f qcow2 $VMHOME/$DISK.qcow2 50G"
  exit
fi

OSDISK="ubuntu-24.04.3-live-server-amd64.iso"
DEFARG="-cpu host -smp 8 -enable-kvm -m 16G -boot c -rtc base=localtime"

HDD="-drive file=$VMHOME/$DISK.qcow2,if=virtio"
CDROM="-drive file=$IMAGES/$OSDISK,media=cdrom"
NETWORK="-device e1000,netdev=network0 -netdev bridge,id=network0"

$QEMU $DEFARG $HDD $CDROM $NETWORK
